version: "3"

services:
  web:
    image: nginx
    ports:
      - "8080:80"  #8080 - порт который мы указываем для подключения, 80 - порт который использует nginx
    volumes:
      - ./web:/usr/share/nginx/html # здесь мы говорим nginx использовать нашу папку со статикой (слушать ее)
  web-docker:
    build: ./web
    ports:
      - "3001:80"
  back:
    build:
      context:  . # файл где лежит docker image в той же папке
      args:
        PORT: '5555' # во время билда образа можем передавать аргументы, если dockerfile образа готов к этому, переменная эта только для образа
    ports:
      - "3131:5555" #3131 - порт который мы указываем для подключения, 5555 - порт котрым image смотрит наружу
    environment:
      PORT: "5555" # чтобы в само наше приложение (app.js) залетели переменные окружения


